# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置 Python 版本
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安装依赖项
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage codecov

    - name: 运行测试并收集覆盖率
      run: |
        coverage run -m unittest discover -s tests
        coverage xml

    - name: 上传覆盖率到 Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        token: 4a07675d-ac1b-481f-b392-b2096882f061
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
